const cfg=window.SUPABASE_CONFIG||{};const ready=cfg.url&&cfg.publishableKey&&!cfg.url.includes('TU-PROYECTO')&&!cfg.publishableKey.includes('TU-PUBLISHABLE');const sb=ready?window.supabase.createClient(cfg.url,cfg.publishableKey):null;const $=s=>document.querySelector(s);let editingId=null;let currentPhotos=[];
if(!sb){$('#loginMsg').textContent='Primero crea config.js con tu URL y Publishable Key de Supabase.'}else{init();}
async function init(){const {data:{session}}=await sb.auth.getSession();if(session) await showDashboard();}
$('#loginBtn').addEventListener('click',async()=>{const email=$('#email').value.trim(),password=$('#password').value;if(!sb)return;$('#loginMsg').textContent='Entrando...';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('#loginMsg').textContent='No pude iniciar sesión: '+error.message;return}await showDashboard()});
$('#logout').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
async function isAdmin(){const {data,error}=await sb.from('admin_users').select('user_id').limit(1);return !error&&data&&data.length>0}
async function showDashboard(){if(!(await isAdmin())){$('#loginMsg').textContent='Este usuario inició sesión, pero no está registrado como administrador en admin_users.';await sb.auth.signOut();return}$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');loadList()}
$('#photos').addEventListener('change',()=>{$('#selectedFiles').innerHTML=[...$('#photos').files].map(f=>`<span class="file-chip">${escapeHtml(f.name)}</span>`).join('')});
$('#cancelEdit').addEventListener('click',resetForm);
$('#memoryForm').addEventListener('submit',async e=>{e.preventDefault();const title=$('#title').value.trim(),date=$('#date').value,description=$('#description').value.trim(),quote=$('#quote').value.trim(),location=$('#location').value.trim(),published=$('#published').checked;if(!title||!date)return;setMsg('formMsg','guardando...');let memoryId=editingId;
if(memoryId){const {error}=await sb.from('memories').update({title,event_date:date,description,quote,location,published,updated_at:new Date().toISOString()}).eq('id',memoryId);if(error){setMsg('formMsg',error.message);return}}
else{const {data,error}=await sb.from('memories').insert({title,event_date:date,description,quote,location,published}).select('id').single();if(error){setMsg('formMsg',error.message);return}memoryId=data.id}
const files=[...$('#photos').files];for(let i=0;i<files.length;i++){const file=files[i];if(file.size>6*1024*1024){setMsg('formMsg',`${file.name} supera 6 MB. Usa una versión más pequeña.`);continue}const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,'-');const path=`${memoryId}/${crypto.randomUUID()}-${safe}`;const {error:upErr}=await sb.storage.from('album-fotos').upload(path,file,{contentType:file.type,upsert:false});if(upErr){setMsg('formMsg','Error subiendo '+file.name+': '+upErr.message);continue}const {error:dbErr}=await sb.from('memory_photos').insert({memory_id:memoryId,storage_path:path,caption:'',sort_order:i});if(dbErr){setMsg('formMsg','Foto subida pero no registrada: '+dbErr.message)}}
setMsg('formMsg','Recuerdo guardado ♡');resetForm();loadList()});
async function loadList(){const {data,error}=await sb.from('memories').select('id,title,event_date,published,memory_photos(id,storage_path)').order('event_date',{ascending:false});if(error){$('#list').textContent=error.message;return}$('#count').textContent=`${data.length} recuerdos`;$('#list').innerHTML=data.map(m=>`<div class="item"><div><div class="item-title">${escapeHtml(m.title)}</div><div class="item-date">${escapeHtml(m.event_date)} · ${m.published?'visible':'oculto'} · ${(m.memory_photos||[]).length} foto(s)</div></div><div class="item-actions"><button data-edit="${m.id}">editar</button><button data-toggle="${m.id}">${m.published?'ocultar':'publicar'}</button><button class="danger" data-delete="${m.id}">borrar</button></div></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editMemory(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>togglePublished(b.dataset.toggle));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteMemory(b.dataset.delete));}
async function editMemory(id){const {data,error}=await sb.from('memories').select('*,memory_photos(*)').eq('id',id).single();if(error)return setMsg('formMsg',error.message);editingId=id;currentPhotos=data.memory_photos||[];$('#formTitle').textContent='Editar recuerdo';$('#memoryId').value=id;$('#title').value=data.title;$('#date').value=data.event_date;$('#location').value=data.location;$('#description').value=data.description;$('#quote').value=data.quote;$('#published').checked=data.published;$('#cancelEdit').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}
async function togglePublished(id){const {data}=await sb.from('memories').select('published').eq('id',id).single();if(data)await sb.from('memories').update({published:!data.published}).eq('id',id);loadList()}
async function deleteMemory(id){if(!confirm('¿Borrar este recuerdo y sus fotos?'))return;const {data}=await sb.from('memory_photos').select('storage_path').eq('memory_id',id);if(data?.length)await sb.storage.from('album-fotos').remove(data.map(x=>x.storage_path));await sb.from('memories').delete().eq('id',id);loadList()}
function resetForm(){editingId=null;currentPhotos=[];$('#memoryForm').reset();$('#published').checked=true;$('#formTitle').textContent='Nuevo recuerdo';$('#cancelEdit').classList.add('hidden');$('#selectedFiles').innerHTML='';}
function setMsg(id,msg){$('#'+id).textContent=msg}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
